language: node_js
node_js:
- 12.6
before_install:
- "pyenv global 3.7.1",
- "pip install -U pip",
- "pip install awscli"
install:
- npm install
script:
- npm test
- npm run build
before_deploy:
  - 'export PATH=~/bin:$PATH'
deploy:
    - provider: s3
      access_key_id: $AWS_ACCESS_KEY_ID
      secret_access_key: $AWS_SECRET_ACCESS_KEY
      bucket: "seafood-fest-serverless"
      local_dir: build
      skip_cleanup: true
      region: $AWS_DEFAULT_REGION
      on:
        branch: development
    - provider: s3
      access_key_id: $AWS_ACCESS_KEY_ID
      secret_access_key: $AWS_SECRET_ACCESS_KEY
      bucket: "map.seafoodfest.org"
      local_dir: build
      skip_cleanup: true
      region: $AWS_DEFAULT_REGION
      on:
        branch: master
after_deploy:
  - aws cloudfront create-invalidation --distribution-id E2AM1R8A87V99T --paths /
