language: node_js
node_js:
- node
install:
- npm install
script:
- npm test
- npm run build
before_deploy:
  - 'curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"'
  - 'unzip awscli-bundle.zip'
  - './awscli-bundle/install -b ~/bin/aws'
  - 'export PATH=~/bin:$PATH'
deploy:
    - provider: s3
      access_key_id: $AWS_ACCESS_KEY_ID
      secret_access_key: $AWS_SECRET_ACCESS_KEY
      bucket: "seafood-fest-serverless"
      local_dir: build
      skip_cleanup: true
      region: $AWS_DEFAULT_REGION
      on:
        branch: development
    - provider: s3
      access_key_id: $AWS_ACCESS_KEY_ID
      secret_access_key: $AWS_SECRET_ACCESS_KEY
      bucket: "map.seafoodfest.org"
      local_dir: build
      skip_cleanup: true
      region: $AWS_DEFAULT_REGION
      on:
        branch: master
after_deploy:
  - aws cloudfront create-invalidation --distribution-id E2AM1R8A87V99T --paths /
